server:
  port: 8080
  compression:
    enabled: true

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/translations}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.batch_size: 1000
        order_inserts: true
        order_updates: true
        generate_statistics: false

app:
  jwt:
    secret: "this-is-a-very-long-hmac-sha256-secret-key-please-change-me-64-CHARS-min"
    issuer: "translation-service"
    expiryMinutes: 60
  seed: ${APP_SEED:false}
